import { THEME_COLORS } from "./utils";

export const styles = {
  dashboardWrapper: {
    minHeight: "100vh",
    background: THEME_COLORS.background,
    color: THEME_COLORS.textPrimary,
    fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
    padding: "0 0 60px",
  },
  header: {
    borderBottom: `1px solid ${THEME_COLORS.borderMuted}`,
    padding: "20px 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    background: THEME_COLORS.background,
    zIndex: 100,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  logoCircle: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: THEME_COLORS.primaryGradient,
  },
  headerTitle: {
    fontWeight: 800,
    fontSize: 18,
    letterSpacing: -0.5,
  },
  headerRight: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  timeframeButton: {
    background: THEME_COLORS.controlBackground,
    border: `1px solid ${THEME_COLORS.cardBorder}`,
    borderRadius: 8,
    padding: "6px 14px",
    fontSize: 13,
    color: THEME_COLORS.textMuted,
    cursor: "pointer",
  },
  exportButton: {
    background: THEME_COLORS.primaryGradient,
    border: "none",
    borderRadius: 8,
    padding: "6px 14px",
    fontSize: 13,
    fontWeight: 600,
    color: THEME_COLORS.textPrimary,
    cursor: "pointer",
  },
  mainContent: {
    padding: "32px",
    maxWidth: 1200,
    margin: "0 auto",
  },
  summaryStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
    marginBottom: 28,
  },
  summaryCard: {
    background: THEME_COLORS.cardBackground,
    border: `1px solid ${THEME_COLORS.cardBorder}`,
    borderRadius: 12,
    padding: "18px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  summaryLabel: {
    fontSize: 12,
    color: THEME_COLORS.noteText,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  summaryValue: {
    fontSize: 28,
    fontWeight: 800,
    letterSpacing: -1,
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 800,
    marginBottom: 16,
    color: THEME_COLORS.textPrimary,
  },
  rowMargin: {
    marginBottom: 16,
  },
  twoColumnGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 32,
  },
  statDetailList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 16,
  },
  statDetailRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 14,
    color: THEME_COLORS.textSecondary,
  },
  boldText: {
    fontWeight: 700,
  },
  stackedBarBg: {
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    background: THEME_COLORS.barBackground,
    marginBottom: 16,
  },
  dividerTop: {
    borderTop: `1px solid ${THEME_COLORS.barBackground}`,
    paddingTop: 14,
  },
  whiteBoldText: {
    fontWeight: 700,
    color: THEME_COLORS.textPrimary,
  },
  columnSubtitle: {
    fontSize: 14,
    fontWeight: 600,
    color: THEME_COLORS.textSecondary,
    marginBottom: 14,
  },
  buttonTabContainer: {
    display: "flex",
    gap: 8,
    marginBottom: 18,
  },
  tabButton: {
    padding: "6px 14px",
    borderRadius: 20,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    transition: "all 0.2s",
  },
  dayButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
    transition: "all 0.2s",
  },
  legendContainer: {
    display: "flex",
    gap: 16,
    marginTop: 8,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: THEME_COLORS.textMuted,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
  },
  horizontalThumbList: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr",
    gap: 16,
  },
  footerNote: {
    marginTop: 24,
    padding: "16px 20px",
    background: THEME_COLORS.noteBackground,
    border: `1px solid ${THEME_COLORS.noteBorder}`,
    borderRadius: 12,
    fontSize: 12,
    color: THEME_COLORS.noteText,
    lineHeight: 1.7,
  },
  apiNotesHeader: {
    color: THEME_COLORS.primary,
    fontWeight: 700,
  },
  codeSnippet: {
    color: THEME_COLORS.textMuted,
  },
};
